---
- name: Update packages on Debian-based systems
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: Install OpenSCAP on Debian-based systems
  ansible.builtin.apt:
    name: "{{ openscap_package_name_debian }}"
    state: present

- name: Install SCAP Security Guide on Debian-based systems
  ansible.builtin.apt:
    name: "{{ ssg_package_name_debian }}"
    state: present

- name: Install unzip package
  ansible.builtin.apt:
    name: "{{ unzip_package_name }}"
    state: present
...
